# fly.toml app configuration file generated for gather-api on 2023-05-04T01:00:37+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gather-api"
primary_region = "nrt"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
